export default {
  namespace: 'users',
  resources: {
    fr: {
      users: 'Utilisateurs',
      user: 'Utilisateur',
      lastName: 'Nom',
      firstName: 'Prénom',
      email: 'Email',
      actions: 'Actions',
      partner: 'Partenaire',
      createUser: 'Créer un nouvel utilisateur',
      edit: 'Modifier',
      delete: 'Supprimer',
      generateCode: 'Générer un code',
      generateMissingCodes: 'Générer les codes manquants',
      codeSent: 'Code envoyé',
      activated: 'Application activée',
      newUser: 'Créer un nouvel utilisateur',
      importUsers: 'Créer à partir d’un fichier CSV',
      all: 'Tous les utilisateurs',
      admin: 'Admins',
      issuers: 'Diffuseurs',
      appUsers: 'Utilisateurs',
      save: 'Enregistrer',
      password: 'Mot de passe',
      blackListed: 'Black listé',
      addingUser: 'Ajout d’un utilisateur',
      editUser: 'Modifier un utilisateur',
      userGroup: "Groupe d'utilisateurs",
      search: 'Rechercher',
      confirmDelete: 'Supprimer ?',
      yes: 'Oui',
      no: 'Non',
      deleteSuccess: 'Utilisateur supprimé',
      deleteError: 'Impossible de supprimer',
      required: 'Champs obligatoire',
      pwdTooLong: 'Mot de passe trop long (max 50 caractères)',
      pwdTooShort: 'Mot de passe trop court (min 6 caractères)',
      tooShort: 'Trop court, 3 caractères minimum',
      noSpace: 'Espaces non autorisés',
      grpRequired: 'Un groupe est requis',
      userSaved: 'Utilisateur enregistré',
      userCreated: ' Utilisateur créé',
      error: 'Une erreur est survenue',
    },
    en: {
      users: 'Users',
      user: 'User',
      lastName: 'Name',
      firstName: 'Firstname',
      email: 'Email',
      actions: 'Actions',
      partner: 'Partner',
      createUser: 'Create user',
      edit: 'Edit',
      delete: 'Delete',
      generateCode: 'Generate a code',
      generateMissingCodes: 'Generate the missing codes',
      codeSent: 'Code sent',
      activated: 'Application activated',
      newUser: 'Create user',
      importUsers: 'Create from CSV file',
      all: 'All users',
      admin: 'Administrators',
      issuers: 'Broadcasters',
      appUsers: 'Users',
      save: 'save',
      password: 'Password',
      blackListed: 'Black listed',
      addingUser: 'Adding an user',
      editUser: 'Edit a user',
      userGroup: 'Users group',
      search: 'Search',
      confirmDelete: 'Delete ?',
      yes: 'Yes',
      no: 'No',
      deleteSuccess: 'User deleted',
      deleteError: 'Impossible to delete',
      required: 'Required field',
      pwdTooLong: 'Password too short (max 50 characters)',
      pwdTooShort: 'Password too short (min 6 characters)',
      tooShort: 'Too short, 3 characters minimum',
      noSpace: 'No spaces allowed',
      grpRequired: 'One group is required',
      userSaved: 'Saved user',
      userCreated: ' Created user',
      error: 'An error occured',
    },
    it: {
      users: 'Utenti',
      user: 'Utente',
      lastName: 'Cognome',
      firstName: 'Nome',
      email: 'Indirizzo mail',
      partner: 'Partner',
      actions: 'Azione',
      createUser: 'Creare un nuovo utente',
      edit: 'Modificare',
      delete: 'Eliminare',
      generateCode: 'Produrre un codice',
      generateMissingCodes: 'Genera i codici mancanti',
      codeSent: 'Codice inviato',
      activated: 'Application activated', // missing
      newUser: 'Creare un nuovo utente',
      importUsers: 'Creare sulla base di un file CSV',
      all: 'Tutti gli utenti',
      admin: 'Amministratori',
      issuers: 'Partner',
      appUsers: 'Utenti',
      save: 'Salva',
      password: "Parola d'ordine",
      blackListed: 'Nella lista nera',
      addingUser: 'Aggiunta di un utente',
      userGroup: 'Gruppo di utenti',
      search: 'Ricerca',
      confirmDelete: 'Delete ?', // missing
      yes: 'Sì',
      no: 'No',
      deleteSuccess: 'Utente eliminato',
      deleteError: 'Si è verificato un errore',
      required: 'Necessario',
      pwdTooLong: 'Password troppo corta (max 50 caratteri)', // to check
      pwdTooShort: 'Password troppo corta (minimo 6 caratteri)',
      tooShort: 'Troppo breve, minimo 3 caratteri',
      noSpace: 'Non sono ammessi spazi',
      grpRequired: 'È richiesto un gruppo',
      userSaved: 'Utente salvato',
      userCreated: 'Utente creato',
      error: 'An error occured', // missing
    },
  },
};
