export default {
  namespace: 'users',
  resources: {
    fr: {
      lastName: 'Nom',
      firstName: 'Prénom',
      email: 'Email',
      edit: 'Modifier un utilisateur',
      newUser: 'Créer un nouvel utilisateur',
      all: 'Tous les utilisateurs',
      admin: 'Admins',
      issuers: 'Diffuseurs',
      appUsers: 'Utilisateurs',
      save: 'Enregistrer',
      password: 'Mot de passe',
      blackListed: 'Black listé',
      userGroup: "Groupe d'utilisateurs",
      required: 'Champs obligatoire',
      pwdTooLong: 'Mot de passe trop long (max 50 caractères)',
      pwdTooShort: 'Mot de passe trop court (min 6 caractères)',
      grpRequired: 'Un groupe est requis',
      userSaved: 'Utilisateur enregistré',
      userCreated: ' Utilisateur créé',
      error: 'Une erreur est survenue',
      invalidEmail: 'Email invalide',
    },
    en: {
      lastName: 'Name',
      firstName: 'Firstname',
      email: 'Email',
      edit: 'Edit user',
      newUser: 'Create user',
      all: 'All users',
      admin: 'Administrators',
      issuers: 'Broadcasters',
      appUsers: 'Users',
      save: 'save',
      password: 'Password',
      blackListed: 'Black listed',
      userGroup: 'Users group',
      required: 'Required field',
      pwdTooLong: 'Password too short (max 50 characters)',
      pwdTooShort: 'Password too short (min 6 characters)',
      grpRequired: 'One group is required',
      userSaved: 'Saved user',
      userCreated: ' Created user',
      error: 'An error occured',
      invalidEmail: 'Invalid email',
    },
    it: {
      lastName: 'Cognome',
      firstName: 'Nome',
      email: 'Indirizzo mail',
      edit: 'Modificare utente',
      newUser: 'Creare un nuovo utente',
      all: 'Tutti gli utenti',
      admin: 'Amministratori',
      issuers: 'Emittenti',
      appUsers: 'Utenti',
      save: 'Salva',
      password: "Parola d'ordine",
      blackListed: 'Nella lista nera',
      userGroup: 'Gruppo di utenti',
      required: 'Campo obbligatorio',
      pwdTooLong: 'Password troppo corta (max 50 caratteri)',
      pwdTooShort: 'Password troppo corta (minimo 6 caratteri)',
      grpRequired: 'È richiesto un gruppo',
      userSaved: 'Utente salvato',
      userCreated: 'Utente creato',
      error: 'Si è verificato un errore',
      invalidEmail: 'Invalid email', // missing
    },
  },
};
